# Generated by Django 4.1 on 2024-07-15 19:30

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_description', models.TextField(max_length=500)),
                ('about', models.TextField(max_length=500)),
                ('project_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct Video URL')], default='youtube', max_length=10)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.folio')),
            ],
        ),
    ]
