# Generated by Django 4.1 on 2024-07-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
