# Generated by Django 4.1 on 2024-07-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_folio_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=500)),
            ],
        ),
    ]
