# Generated by Django 4.1 on 2024-07-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_about_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
