# Generated by Django 4.1 on 2024-07-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_folio_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folio',
            name='about',
        ),
    ]
