# Generated by Django 4.1 on 2024-07-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_stack_stack_framework_stack_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='framework',
            new_name='framework_image',
        ),
        migrations.RenameField(
            model_name='stack',
            old_name='language',
            new_name='language_image',
        ),
    ]
