# Generated by Django 4.1 on 2024-07-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_framework_stack_framework_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
